export const FETCH_LOCATION_DATA = 'FETCH_DATA'

export const CHANGE_SEARCH_TERM = 'CHANGE_SEARCH_TERM'

export const LOCATIONS_DATA_COUNT = 'LOCATIONS_DATA_COUNT'

export const AREA_CHECK_BOX_CHANGE = 'AREA_CHECK_BOX_CHANGE'